### ISSUE TITLE
IsDuplicateFilter: 'skipDuplicates' still returns duplicates

### ISSUE THREAD

**Issue by joelhulen** [EventRegistry/event-registry-node-js#2]
When I submit a `ComplexArticleQuery`, passing in the `isDuplicateFilter: 'skipDuplicates'` argument, though most duplicates are removed, there still are a few when executing a query only containing today's date as the `dateStart` value, 'eng' for `lang`, and 'general/ERtop25' for the `sourceGroupUri` value.

Please refer to the attached file containing my search results. As an example you will find the `816045864` uri twice in the articles collection. If I conduct a keyword search for "Quatari" and "Gaza", only one result for the article is returned instead of the duplicate.

[eventregistry-duplicates.txt](https://github.com/EventRegistry/event-registry-node-js/files/1737322/eventregistry-duplicates.txt)

**Comment by gregorleban** [comment]
Hi Joel,
can you provide us with a full sample code that you are executing?Currently we
never had cases where we would be providing the same article multiple times.
Thank you!  





On Mon, Feb 19, 2018 4:33 PM, Joel Hulen notifications@github.com  wrote:
When I submit a ComplexArticleQuery, passing in the isDuplicateFilter:
'skipDuplicates'  argument, though most duplicates are removed, there still are
a few when executing a query only containing today's date as the dateStart 
value, 'eng' for lang, and 'general/ERtop25' for the sourceGroupUri  value.

Please refer to the attached file containing my search results. As an example
you will find the 816045864  uri twice in the articles collection. If I conduct
a keyword search for "Quatari" and "Gaza", only one result for the article is
returned instead of the duplicate.

eventregistry-duplicates.txt

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or mute the thread.






Gregor Leban

CEO & Co-founder of Event Registry

Phone: 00386-31-321-804 | Skype: gregorleban

Find us on Twitter, Facebook  or read our blog

**Comment by gregorleban** [comment]
Hi Joel,
we were able to reproduce the error. Also, we've identified the issue and fixed
it already so you should not see duplicates anymore.
Best regards,Gregor  





On Tue, Feb 20, 2018 8:57 AM, Gregor Leban gregor@eventregistry.org  wrote:
Hi Joel,
can you provide us with a full sample code that you are executing?Currently we
never had cases where we would be providing the same article multiple times.
Thank you!  





On Mon, Feb 19, 2018 4:33 PM, Joel Hulen notifications@github.com  wrote:
When I submit a ComplexArticleQuery, passing in the isDuplicateFilter:
'skipDuplicates'  argument, though most duplicates are removed, there still are
a few when executing a query only containing today's date as the dateStart 
value, 'eng' for lang, and 'general/ERtop25' for the sourceGroupUri  value.

Please refer to the attached file containing my search results. As an example
you will find the 816045864  uri twice in the articles collection. If I conduct
a keyword search for "Quatari" and "Gaza", only one result for the article is
returned instead of the duplicate.

eventregistry-duplicates.txt

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or mute the thread.






Gregor Leban

CEO & Co-founder of Event Registry

Phone: 00386-31-321-804 | Skype: gregorleban

Find us on Twitter, Facebook  or read our blog






Gregor Leban

CEO & Co-founder of Event Registry

Phone: 00386-31-321-804 | Skype: gregorleban

Find us on Twitter, Facebook  or read our blog

**Comment by joelhulen** [comment]
Thank you! I was just about to send you my code :)
